version: 2
jobs:
  test:
    docker:
      - image: artsy/hokusai
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: hokusai test
  push:
    docker:
      - image: artsy/hokusai
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Push to hokusai
          command: hokusai registry push --tag $CIRCLE_SHA1 --force --overwrite
  deploy-staging:
    docker:
      - image: artsy/hokusai
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Configure hokusai
          command:
            hokusai configure --kubectl-version 1.10.7 --s3-bucket artsy-citadel
            --s3-key k8s/config --platform linux
      - run:
          name: Validate Kubernetes Yaml
          command: |
            kubectl --context staging apply -f ./hokusai/staging.yml --dry-run
      - run:
          name: Update staging branch
          command:
            git push git@github.com:artsy/kaws.git $CIRCLE_SHA1:staging --force
      - run:
          name: Deploy staging assets
          command: hokusai staging deploy $CIRCLE_SHA1
  deploy-production:
    docker:
      - image: artsy/hokusai
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Configure hokusai
          command:
            hokusai configure --kubectl-version 1.10.7 --s3-bucket artsy-citadel
            --s3-key k8s/config --platform linux
      - run:
          name: Validate Kubernetes Yaml
          command: |
            kubectl --context production apply -f ./hokusai/production.yml --dry-run
      - run:
          name: Deploy production assets
          command: hokusai production deploy $CIRCLE_SHA1 --git-remote origin

workflows:
  version: 2
  default:
    jobs:
      - test:
          context: hokusai
          filters:
            branches:
              ignore:
                - staging
      - push:
          filters:
            branches:
              only:
                - master
                - release
          requires:
            - test
      - deploy-staging:
          filters:
            branches:
              only: master
          requires:
            - push
      - deploy-production:
          filters:
            branches:
              only: release
          requires:
            - push
