apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kaws-web
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kaws
        component: web
        layer: application
      name: kaws-web
    spec:
      containers:
        - name: kaws-web
          envFrom:
            - configMapRef:
                name: kaws-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/kaws:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kaws
    component: web
    layer: application
  name: kaws-web
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4000
  selector:
    app: kaws
    component: web
    layer: application
  type: ClusterIP
